### ISSUE TITLE
DOC: How to call NewWave tasks incrementally?

### ISSUE THREAD

**Issue by macta** [skaplar/NewWave#5] opened 2019-09-26 15:35 UTC
I'm not sure if this question makes sense, however if you want to use NewWave in an incremental fashion (for example, go to the next task on a web page submission, and then render that as a result) - its not clear how you do that from the examples. Everything is shown as ```engine startEngine``` which runs everything end to end without pause, however I'm wondering if there is a concept like ```engine runNext```?

**Comment by noha** [comment] 2019-10-29 12:43
I'm also interested when the model evolves to a point where states become stable until further events arrive. Can you explain a bit?

**Comment by skaplar** [comment] 2019-10-31 13:59
So if I understand the question correctly, basically
WaveExecutor>>tryToExecuteNext: aCompletedNode

This is the one called by the engine when you start it, and when the task is finished.
In here, we get the next node to be executed, and send it to be executed
self execute: tmp.

Execute determines the type of executor for the node(or how I named it eg. TaskEventBehavior>>performExecution: elemToExecute executor: wave ), and then starts executing it. Then TaskEventBehavior has the responsibility to call the next one when it finishes executing.

It is also possible to call them manually in NewWave, it's just the way I made it run when startEngine is called.

**Comment by noha** [comment] 2019-11-05 13:29
Thank you. I think the problem is that the model is not familiar to us so a description of the basic classes and their relationship would be great. 

An answer to @macta might be that it depends on the type of node you use. There are events which are single action. If you look at CustomTask you might find what you are looking for. A task is activate by sending #value and when the task is finished you call #complete on the task which makes the flow continue.

If this is acknowledged we might close this issue?

**Comment by skaplar** [comment] 2019-11-08 16:55
I'll close this for now, if needed we will reopen it.

**Closed as completed by skaplar** 2019-11-08 16:55 UTC
